name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Archive build output
        if: success()
        run: |
            mkdir -p build
            cp -r app/SampleApp.py build/
            zip -r build/output.zip build/

      - uses: actions/upload-artifact@v3
        with:
            name: python-build
            path: build/output.zip
        