name: PythonBuildPackage-CD-POC

on:
    workflow_run:
        workflows:
        - Build Artifact
        types:
        - completed

jobs:
   deployment:
        runs-on: ubuntu-latest

        environment: poc

        steps:

          - name: Download artifacts
            uses: actions/download-artifact@v4
            with:
                name: python-build
                path: build/output.zip

          - name: Extract
            run: unzip output.zip -d deployment/

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                python-version: 3.12

          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install -r deployment/requirements.txt

          - name: Deploy app
            run: |
                cd deployment/
                python SampleApp.py