name: PythonBuildPackage-CICD-POC

on: 
    workflow_dispatch:  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
            python-version: '3.12'
            cache: 'pip'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Displa Branch Name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      - name: Run tests
        run: |
            echo "This is a Test 1!!!"
            echo "This is a Test 2!!!"
            echo "This is a Test 3!!!"

      - name: Archive build output
        if: success()
        run: |
            mkdir -p build
            cp -r app/SampleApp.py build/
            # zip -r build/output.zip build/

      - uses: actions/upload-artifact@v4
        with:
            name: python-app
            path: build

  deploy:
        permissions:
            contents: none
        runs-on: ubuntu-latest
        environment: poc
        needs: build

        steps:

          - name: Download artifacts
            uses: actions/download-artifact@v4
            with:
                name: python-app
                path: .

          - name: Set up Python
            uses: actions/setup-python@v4
            with:
                    python-version: 3.12

          - name: Install dependencies
            run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt

          - name: Deploy app
            run: |
                    echo "READT to execute #python SampleApp.py"
        